# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

dist: trusty  # for a more recent ImageMagick

julia:
  - 1.0

env:
  - JULIA_CPU_CORES=2 # travis vm only has 2 cores, but Julia reads the number of hardware cores

before_install:
  - sudo apt-get update 
  - sudo apt-get install -y tesseract-ocr

notifications:
  email:
    on_success: always
    on_failure: never

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --color=yes -e 'using InteractiveUtils; versioninfo(); import Pkg; Pkg.clone(pwd()); Pkg.build("OCReract")'
  - julia --color=yes -e 'import Pkg; Pkg.test("OCReract"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("OCReract")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'