# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 0.6

env:
  - JULIA_CPU_CORES=2 # travis vm only has 2 cores, but Julia reads the number of hardware cores

before_install:
  - sudo apt-get update 
  - sudo apt-get install -y tesseract-ocr

notifications:
  email:
    on_success: always
    on_failure: never

script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("OCReract")'
  - julia --code-coverage test/runtests.jl

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("OCReract"); Pkg.test("OCReract"; coverage=true)'

after_success:
- julia -e 'cd(Pkg.dir("OCReract")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'